---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://api.openaq.org/v3/locations?coordinates=D51.549424,-0.165178&radius=1000
polling_headers: 'X-API-Key: PUT_YOUR_OPENAQ_API_KEY_HERE'
name: Air Quality from OpenAQ
refresh_interval: 60
