---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://api.openaq.org/v3/locations?coordinates=D51.549424,-0.165178&radius=1000
polling_headers: 'X-API-Key: c391bed55f1ccd3cee9fbdf218a237f630bb1f087256faad915cc476385c55d0'
name: Air Quality from OpenAQ
refresh_interval: 60
